# The name of the workflow
name: poly Deploy dev

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
    secrets:
      EC2_SSH_KEY:
        required: true
      EC2_HOST_DEV:
        required: true
      EC2_USERNAME:
        required: true
      APP_DEV_CERT:
        required: true
      TELEGRAM_TOKEN_DEV:
        required: true
      S3_BUCKET_DEV:
        required: true
  workflow_dispatch:
    inputs:
      image:
        required: true
        type: string
        description: "Docker image to deploy"

env:
  REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
  REPO_NAME: ${{ github.event.repository.name }}
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST_DEV }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          cat > ~/.ssh/config << EOF
          Host ec2
              HostName $EC2_HOST
              User $EC2_USERNAME
              IdentityFile ~/.ssh/private_key
              StrictHostKeyChecking no
          EOF

      - name: Copy script to EC2
        run: |
          # Clone repository if it doesn't exist, otherwise pull latest changes
          ssh ec2 "if [ -d ~/${REPO_NAME} ]; then \
          cd ~/${REPO_NAME} && git checkout dev3 && git pull; \
          else \
          git clone --branch dev3 ${REPO_URL} ~/${REPO_NAME}; \
          fi"

      - name: Execute script on EC2
        run: |
          ssh ec2 "cd $REPO_NAME && \
          APP_DEV_CERT='${{ secrets.APP_DEV_CERT }}' \
          bash deploy_dev.sh ~/${REPO_NAME} ${{ secrets.TELEGRAM_TOKEN_DEV }} ${{ secrets.S3_BUCKET_DEV }}"


