version: '3.8'

services:
  polybot:
    image: "${IMG_NAME}"
    restart: always
    env_file:
      - .env
    ports:
      - "8443:8443"
    volumes:
      - /home/ubuntu/polybot_cer.crt:/app/polybot_cer.crt