name: Polybot Build Dev

on:
  push:
    branches:
      - dev3
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "Building Docker image for dev3 branch"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Boto3
        run: pip install boto3

      - name: Build and Push Docker Image
        run: |
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
          img_name="majdabbas99/polybot_build_dev:${{github.run_number}}"
          docker buildx build --push --build-arg SECRETS='majd/dev/polybot' -t $IMAGE_NAME .
