# The name of the workflow
name: Polybot Build Dev

on:
  push:
    branches:
     - dev3
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: Build Docker image
       env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST_DEV }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
          REPO_NAME: ${{ github.event.repository.name }}
       run: |
         docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
         
         img_name=${{ secrets.DOCKERHUB_USERNAME }}/polybot_build_dev:${{github.run_number}}
         
         # same docker_image to pass it to the next workflow 
         echo "image=$img_name" >> $GITHUB_OUTPUT
          
         # build & push the image 
         docker build --push -t $img_name  .

  Deploy:
    needs: Build
    uses: ./.github/workflows/deploy_dev.yaml
    with:
      image: ${ steps.Build.outputs.image }