# The name of the workflow
name: Polybot Build Dev

on:
  push:
    branches:
     - dev3
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: Build Docker image
       env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
       run: |
         docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
         
         img_name=${{ secrets.DOCKERHUB_USERNAME }}/Polybot_Build_Dev:${{github.run_number}}
         
         # same docker_image to pass it to the next workflow 
         echo "image=$img_name" >> $GITHUB_OUTPUT
          
         # build & push the image 
         docker build --push -t $img_name  .

  Deploy:
    needs: Build
    uses: ./.github/workflows/deploy-dev.yaml
    with:
      image: ${ steps.Build.outputs.image }