# The name of the workflow
name: Polybot Build Dev

on:
  push:
    branches:
     - dev3
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: Build Docker image
       env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

       run: |
         docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
         
         img_name=${{ secrets.DOCKERHUB_USERNAME }}/polybot_build_dev:${{github.run_number}}
         
         # same docker_image to pass it to the next workflow 
         echo "image=$img_name" >> $GITHUB_OUTPUT
         echo "what_is_that=$img_name"
         # build & push the image 
         #docker build --push -t $img_name  .

  Deploy:
    needs: Build
    uses: ./.github/workflows/deploy_dev.yaml
    with:
      image: ${ steps.Build.outputs.image }
    secrets:
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      EC2_HOST_DEV: ${{ secrets.EC2_HOST_DEV }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      APP_DEV_CERT: ${{ secrets.APP_DEV_CERT }}
      TELEGRAM_TOKEN_DEV: ${{ secrets.TELEGRAM_TOKEN_DEV }}
      S3_BUCKET_DEV: ${{ secrets.S3_BUCKET_DEV }}
