name: Polybot Build Dev

on:
  push:
    branches:
     - dev4
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Echo Docker build start
        run: echo "Building Docker image for dev4 branch"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and Push Docker Image
        run: |
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
          IMG_NAME="${{ secrets.DOCKERHUB_USERNAME }}/polybot_dev_Image:${{ github.run_number }}"
          docker build -t "$IMG_NAME" .
          docker push "$IMG_NAME"

          aws ssm put-parameter \
            --name "/majd/dev/polybot_image_name" \
            --value "$IMG_NAME" \
            --type "SecureString" \
            --overwrite \
            --region "eu-west-1"